[workspace]
authors = ["Kevin Mills <millsks@gmail.com>"]
channels = ["conda-forge"]
name = "data-structures-and-algorithms"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.13.*"
numpy = ">=2.4.3,<3"
pandas = ">=3.0.2,<4"
